sonar.projectKey=l01-10h37_onboarding-and-homescreen
sonar.organization=l01-10h37

sonar.sources=.
sonar.exclusions=**/*.test.tsx,**/node_modules/**

sonar.tests=.
sonar.test.inclusions=**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
