name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # chạy test + tạo coverage
      - name: Run tests with coverage
        run: npm test -- --coverage --all

      #  debug xem có coverage không
      - name: Check coverage file
        run: ls -R coverage

      #  SonarCloud scan (FIX CHÍNH)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=l01-10h37_onboarding-and-homescreen
            -Dsonar.organization=l01-10h37
            -Dsonar.sources=app
            -Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
